language: ruby

rvm:
  - 1.9.3

branches:
  only:
    - stable

bundler_args: --without development

before_install:
  - sudo add-apt-repository -y ppa:gijzelaar/opencv2.4
  - sudo apt-get update
  - sudo apt-get install libopencv-core2.4 libopencv-highgui2.4 libopencv-imgproc2.4 libopencv-features2d2.4 libopencv-calib3d2.4

script: bundle exec rake 

notifications:
  email: 
    recipients:
      - aaron.marburg@pg.canterbury.ac.nz
    on_success: change
    on_failure: always
