language: ruby

rvm:
  - 1.9.3

branches:
  only:
    - stable

bundler_args: --without development

before_install:
  - sudo add-apt-repository -y ppa:gijzelaar/opencv2.3
  - sudo apt-get update
  - sudo apt-get install libopencv-core2.3 libopencv-highgui2.3 libopencv-imgproc2.3 libopencv-features2d2.3 libopencv-calib3d

script: bundle exec rake 

notifications:
  email: 
    recipients:
      - aaron.marburg@pg.canterbury.ac.nz
    on_success: change
    on_failure: always
